name: CI with Sonar + Automation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sonar-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      -  name: Install dependencies
         working-directory: ./backend
         run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm run test:cov

      - name: Install & Test Frontend
        run: |
          cd frontend
          npm install
          npm test -- --coverage

      - name: Run SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Trigger QA Automation
        run: |
          curl -X POST https://api.github.com/repos/<your-qa-repo>/actions/workflows/run-tests.yml/dispatches \
          -H "Authorization: Bearer ${{ secrets.QA_REPO_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"ref":"main"}'
